### ISSUE TITLE
Add documentation for Paninian Syntacto-Semantic relations 

### ISSUE THREAD

**Issue by MayankGoel28** [globalwordnet/gwadoc#18]
https://ltrc.iiit.ac.in/Publications/pan_english.html
https://cdn.iiit.ac.in/cdn/ltrc.iiit.ac.in/downloads/nlpbook/nlp-panini.pdf
https://semioticon.com/sio/courses/dynamical-models-in-semiotics-semantic/indian-grammatical-theory/

The karak semantic relations are commonly used for Indian Languages. This is essentially a feature request, but I'd like to work on it.

**Comment by goodmami** [comment]
Thanks for the links but those are very large documents and I don't immediately see what you are referring to. Can you please summarize what the feature is that you're requesting? Is it a new relation type?

**Comment by MayankGoel28** [comment]
So the Sanskrit linguist Panini used six semantic roles (karak) in Sanskrit grammar. They're like cases, but different in the sense that they're more semantic in nature. In Indian Languages, they're used for most research that I have seen because of how suited it is t. In LTRC, IIIT Hyderabad, we have used these because of its suitability to Indian Languages because most ILs are (relatively) free-order. Note that the position (syntax) information is secondary to the semantic role of the entity.

**Comment by MayankGoel28** [comment]
@goodmami https://en.wikipedia.org/wiki/Declension#Sanskrit, this should be a short enough introduction for you to peruse.

**Comment by goodmami** [comment]
@MayankGoel28 thanks for explaining. It would be problematic if we defined new localized relations for every language, so why can't we reuse some existing ones?

* agent / kartṛ  -> [agent](https://globalwordnet.github.io/gwadoc/#agent)
* patient / karman -> [patient](https://globalwordnet.github.io/gwadoc/#patient)
* means / karaṇa -> [instrument](https://globalwordnet.github.io/gwadoc/#instrument)
* recipient / sampradāna -> ?? (like dative case in syntax)
* source / apādāna -> [source_direction](https://globalwordnet.github.io/gwadoc/#source_direction)?
* relation / sambandha -> ?? (like genitive case in syntax)
* locus / adhikaraṇa -> [location](https://globalwordnet.github.io/gwadoc/#location)
* address / sambodhana -> ??  (like vocative case in syntax)

I'm not familiar with Sanskrit so I'm not quite understanding why some of these are semantic relations rather than syntactic, and I think we should avoid further expansion into modelling syntactic roles. Could the "relation" role be modeled with [meronym](https://globalwordnet.github.io/gwadoc/#meronym) or some subtype?

**Comment by MayankGoel28** [comment]
@goodmami Just to be clear, karak relations aren't just for Sansrkit, but are a form of relation more suited to free-order languages (as it relies on both position and semantics for classification), and is used for research into Indian Languages. I do understand your point, a lot of it is similar to what already exists. I've certainly not seen karak relations being used outside Indian Languages. Subtypes of meronym could be a good way to add some roles. 

We could certainly reuse old roles, it would just require a slight modification to docs to give the same output for a different label.

**Comment by goodmami** [comment]
One other thing you could do for now is use the [other](https://globalwordnet.github.io/gwadoc/#other) relation with a `dc:type` attribute specifying your particular relation. But as much as possible you should try to reuse existing relations. Your own project can then describe how you're using "agent" for kartṛ, etc.

However, do note that this repository is for the documentation of the various relation types. If you want to propose new ones (e.g., for "recipient"), they'd need to be added to the schemas first, so try https://github.com/globalwordnet/schemas.

**Comment by MayankGoel28** [comment]
@goodmami Okay, I understand! Thanks for your comments.

**Comment by gconnect** [comment]
I think this issue can be  closed if we are not moving forward with it?

**Comment by goodmami** [comment]
Yes I think so. Thanks
